language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

sudo: false

env:
  - AZURE_STORAGE_CONNECTION_STRING="UseDevelopmentStorage=true;"

before_script:
  - composer install --prefer-dist -o

script: 
  - ./vendor/bin/phpunit -c phpunit.local.xml.dist
